library(martini)
data(examplegwas)

set.seed(0)

test_that("default args are being set", {
  expect_equal(get_shake_settings()$nParameters, 10)
  expect_equal(get_shake_settings()$folds, 10)
  expect_equal(get_shake_settings()$autoParameters, TRUE)
  expect_equal(get_shake_settings()$lambdas, rep(0, 10))
  expect_equal(get_shake_settings()$etas, rep(0, 10))
  expect_equal(get_shake_settings()$test_statistic, 0)
  expect_equal(get_shake_settings()$gridsearch_depth, 1)
  expect_equal(get_shake_settings()$selection_criterion, 1)
  expect_equal(get_shake_settings()$seed, 0)
  expect_equal(get_shake_settings()$selection_ratio, 0.8)
  expect_equal(get_shake_settings()$dump_intermediate_results, TRUE)
  expect_equal(get_shake_settings()$evaluateObjective, FALSE)
})

test_that("default we can change values", {
  expect_equal(get_shake_settings(nParameters = 13)$nParameters, 13)
  expect_equal(get_shake_settings(folds = 13)$folds, 13)
  expect_equal(get_shake_settings(autoParameters = F, lambdas = 3, etas = c(1,2))$autoParameters, F)
  expect_equal(get_shake_settings(autoParameters = F, lambdas = 3, etas = c(1,2))$lambdas, 3)
  expect_equal(get_shake_settings(autoParameters = F, lambdas = 3, etas = c(1,2))$etas, c(1,2))
  expect_equal(get_shake_settings(test_statistic = 3)$test_statistic, 3)
  expect_equal(get_shake_settings(gridsearch_depth = 2)$gridsearch_depth, 2)
  expect_equal(get_shake_settings(selection_criterion = 3)$selection_criterion, 3)
  expect_equal(get_shake_settings(seed = 9)$seed, 9)
  expect_equal(get_shake_settings(selection_ratio = 0.654)$selection_ratio, 0.654)
  expect_equal(get_shake_settings(dump_intermediate_results = F)$dump_intermediate_results, F)
  expect_equal(get_shake_settings(evaluateObjective = T)$evaluateObjective, T)
})