# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_regression_stats <- function(X, Y) {
    .Call('_martini_get_regression_stats', PACKAGE = 'martini', X, Y)
}

maxflow <- function(lW, c) {
    .Call('_martini_maxflow', PACKAGE = 'martini', lW, c)
}

read_gwas <- function(pedBasename, phenoFile, netPath, encoding, maf) {
    .Call('_martini_read_gwas', PACKAGE = 'martini', pedBasename, phenoFile, netPath, encoding, maf)
}

run_shake <- function(X, Y, network, userSettings) {
    .Call('_martini_run_shake', PACKAGE = 'martini', X, Y, network, userSettings)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_martini_RcppExport_registerCCallable', PACKAGE = 'martini')
})
