# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_scones_testing <- function(eta, lambda, nparams, statistic) {
    .Call('rscones2_create_scones_testing', PACKAGE = 'rscones2', eta, lambda, nparams, statistic)
}

maxflow <- function(lW, A) {
    .Call('rscones2_maxflow', PACKAGE = 'rscones2', lW, A)
}

rcpp_hello <- function() {
    .Call('rscones2_rcpp_hello', PACKAGE = 'rscones2')
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('rscones2_RcppExport_registerCCallable', PACKAGE = 'rscones2')
})
